### ISSUE TITLE
Don't fail if provided scriptPubKey is already set

### ISSUE THREAD

**Issue by louneskmt** [bitcoinerlab/discovery#13]
I tried to fetch an address belonging to a ranged descriptor I had already fetched. What's the rationale of failing the fetch in that case, instead of silently proceeding?

**Comment by louneskmt** [comment]
Thanks for the detailed answer. The rationale makes sense. 

How do you handle fetching the descriptor of a single address belonging deep down to an existing ranged descriptor? Using a gap limit?

**Comment by landabaso** [comment]
> Thanks for the detailed answer. The rationale makes sense.
> 
> How do you handle fetching the descriptor of a single address belonging deep down to an existing ranged descriptor? Using a gap limit?

Yes. Either using the `gapLimit` or passing the specific `index` you're interested in the `fetch` function.
You can take a loop to the API [here](https://bitcoinerlab.com/modules/discovery/api/classes/_Internal_.Discovery.html#fetch) or compile it locally by `npm run docs`.

**Comment by louneskmt** [comment]
In the context of a multi-user app, does that mean each user needs to have their own `Discovery` instance? Two accounts owned by the same user could put different descriptors that point to the same scriptPubKey (account 1: xpub, account 2: single address). There are always edge-cases to consider.

While the rationale made sense at first, I'm still not convinced.

**Comment by landabaso** [comment]
Yes, different 'wallets' should use separate instances to ensure that they do not share any data. By 'wallet,' I mean a set of descriptors that belongs to a single entity or person. This is important for maintaining privacy.
